### ISSUE TITLE
I could't run npm install

### ISSUE THREAD

**Issue by chyuaner** [alanreid/bravia#1]
I could't run `npm install`.
Show message:

```
yuan@Yuan-MacBook-Pro sony/bravia (master) » npm install
npm WARN package.json bravia@1.0.0 No repository field.
npm WARN package.json bravia@1.0.0 license should be a valid SPDX license expression

> socketwatcher@0.2.1 install /Users/yuan/Desktop/sony/bravia/node_modules/arpjs/node_modules/pcap/node_modules/socketwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many
      arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/yuan/.node-gyp/2.2.1/deps/v8/include/v8.h:4188:3: note: 'New' declared
      here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yuan/Desktop/sony/bravia/node_modules/arpjs/node_modules/pcap/node_modules/socketwatcher
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> typechecker@2.0.8 preinstall /Users/yuan/Desktop/sony/bravia/node_modules/arpjs/node_modules/getmac/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v2.2.1
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! socketwatcher@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socketwatcher@0.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the socketwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls socketwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yuan/Desktop/sony/bravia/npm-debug.log
```

**Comment by alanreid** [comment]
Hi, 

Could you include your node and npm versions?

Thanks

**Comment by tilledminds** [comment]
Hi Alan -

I'm getting the same issue. My NPM version is 2.14.7 and Node is 4.2.1

Thanks,
Paul

**Comment by alanreid** [comment]
Hi Paul,

Thanks for reporting this. I'll try to reproduce the issue and have it fixed. 
I'll keep you posted.

Alan

**Comment by tilledminds** [comment]
Thanks Alan.

**Comment by alanreid** [comment]
Hi @chyuaner, @tilledminds 

I was able to fix this issue. arpjs (an external dependency) was getting an outdated version of another dependency, so I removed it altogether.

Please try again now, hopefully it's solved for good now.

Thanks!

**Comment by tilledminds** [comment]
Awesome Alan - it works.

Thanks,
Paul
