### ISSUE TITLE
that is not defined

### ISSUE THREAD

**Issue by sweebee** [alanreid/bravia#9]
Tested your updates but i get:

```
ReferenceError: that is not defined
    at updateCookieJar (/home/pi/bravia/lib/index.js:242:3)
    at /home/pi/bravia/lib/index.js:188:9
    at /home/pi/bravia/lib/index.js:161:7
    at Request._callback (/home/pi/bravia/lib/index.js:225:7)
    at Request.self.callback (/home/pi/bravia/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/pi/bravia/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
```

**Comment by alanreid** [comment]
Sorry for that, can you check now?

**Comment by sweebee** [comment]
nope:

```
/home/pi/bravia/lib/index.js:238
Bravia.prototype.updateCookieJar = (callback) {
                                              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/bravia/demo.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by alanreid** [comment]
Buh, sorry, I missed something. Let me know if it works now!

**Comment by sweebee** [comment]
Yes works, but it keeps asking for the code again.

**Comment by alanreid** [comment]
It works now on the TV I'm testing it with. What model/firmware version do you have?

**Comment by sweebee** [comment]
Model: KDL-50W828B
Software: PKG2.704EUA

**Comment by sweebee** [comment]
This fork works fine: https://github.com/Easen/bravia

**Comment by alanreid** [comment]
Thanks! Looks like he just fixed the cookie store and used his version instead. I'll take that approach then if it works
